spring:
  application:
    name: spring-cloud-web-hello-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  zipkin:
    base-url: http://192.168.10.200:9411
  boot:
    admin:
      client:
        url: http://192.168.10.200:8084

server:
  port: 8765

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.10.200:8761/eureka/